name: Create Struct Files

on:
  push:
    branches: [ main ]


jobs:
  consolidate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: generate struct files
        run: npm run consolidate-structs
      - name: modify and push
        uses: EndBug/add-and-commit@v5
        with:
          add: -A
          message: "updated struct file(s)"
          push: true
          tag: bot-action
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
